# ~/.config/starship/bash.toml

# â”€â”€ palette (Dracula-ish)
[palettes.custom]
color13 = '#390c00'
color15 = '#f1dfda'
color10 = '#ffb59d'
cyan    = '#8be9fd'
red     = '#ff5555'
green   = '#50fa7b'
orange  = '#ffb86c'
pink    = '#ff79c6'
blue    = '#6272a4'

# â”€â”€ prompt formats
add_newline = false

format = """
â•­â”€ [$username](bg:color13 fg:color15)\
[$os](bg:color13 fg:color15)\
[$directory](bg:color10 fg:color13)\
$git_branch$git_status
â•°â”€ â¯â¯ """

right_format = """$nodejs$python$java"""

# â”€â”€ segments
[username]
show_always = true
format = "[ $user ]($style)"
style = "bg:color13 fg:color15"

[os]
format = "[ğŸ§]($style)"
style = "bg:color13 fg:color15"

[directory]
format = "[ $path ]($style)"
style = "bg:color10 fg:color13"
truncation_length = 0

[git_branch]
symbol = ""
format = "[ $branch ]($style)"
style  = "fg:color13"

[git_status]
ahead  = " â‡¡$count"
behind = " â‡£$count"
modified = "*"
untracked = "? "
up_to_date = "ï€Œ "
conflicted = "î®« "
format = "[ï„“$ahead$behind$modified]($style)"
style = "fg:cyan"

[nodejs]
format = "[îœ˜ $version]($style)"
style  = "bg:green fg:color13"

[python]
format = "[îœ¼ $version]($style)"
style  = "bg:green fg:color13"

[java]
format = "[îœ¸ $version]($style)"
style  = "bg:pink fg:color13"
